// ข้อมูลอาหาร (ผมใส่ให้เยอะๆ ครบทุกประเภทเลยครับ)
const foodData = [
    // --- โซนอาหารเหนือ / ไทใหญ่ (ตามที่เคยขอไว้) ---
    { name: "ข้าวซอยไก่", cal: 500, type: "noodle", img: "photo/ข้าวซอยไก่.JPG" },
    { name: "ขนมจีนน้ำเงี้ยว", cal: 350, type: "noodle", img: "photo/ขนมจีนน้ำเงี้ยว.JPG" },
    { name: "แกงฮังเลหมู + ข้าวเหนียว", cal: 600, type: "rice", img: "photo/เเกงฮังเลหมู.JPG" },
    { name: "ไส้อั่ว + ข้าวเหนียว", cal: 550, type: "rice", img: "photo/ไส้อั่ว.JPG" },
    { name: "ลาบหมูคั่ว", cal: 250, type: "rice", img: "photo/ลาบหมูคั่ว.jpg" },
    { name: "น้ำพริกหนุ่ม + แคบหมู", cal: 350, type: "clean", img: "photo/น้ำพริกหนุ่ม.JPG" },
    { name: "แกงโฮะ", cal: 400, type: "rice", img: "photo/เเกงโฮะ.JPG" },
    { name: "จอผักกาด", cal: 150, type: "clean", img: "photo/จอผักกาด.JPG" },

    // --- เมนูเส้น / ก๋วยเตี๋ยว ---
    { name: "ก๋วยเตี๋ยวเรือหมูน้ำตก", cal: 450, type: "noodle", img: "photo/ก๋วยเตี๋ยวเรือหมูน้ำตก.png" },
    { name: "บะหมี่เกี๊ยวหมูแดง", cal: 400, type: "noodle", img: "photo/บะหมี่เกี๊ยวหมูแดง.JPG" },
    { name: "ผัดไทยกุ้งสด", cal: 550, type: "noodle", img: "photo/ผัดไทยกุ้งสด.JPG" },
    { name: "ราดหน้าหมูหมัก", cal: 450, type: "noodle", img: "photo/ราดหน้าหมูหมัก.JPG" },
    { name: "ผัดซีอิ๊วหมู", cal: 600, type: "noodle", img: "photo/ผัดซีอิ๊วหมู.JPG" },
    { name: "สุกี้น้ำรวมมิตร", cal: 350, type: "noodle", img: "photo/สุกี้น้ำรวมมิตร.JPG" },
    { name: "สุกี้แห้งไก่", cal: 400, type: "noodle", img: "photo/สุกี้แห้งไก่.JPG" },
    { name: "ก๋วยจั๊บน้ำข้น", cal: 500, type: "noodle", img: "photo/ก๋วยจั๊บน้ำข้น.JPG" },
    { name: "เย็นตาโฟต้มยำ", cal: 450, type: "noodle", img: "photo/เย็นตาโฟต้มยำ.JPG" },
    { name: "บะหมี่เป็ดตุ๋น", cal: 450, type: "noodle", img: "photo/บะหมี่เป็ดตุ๋น.JPG" },
    { name: "มาม่าต้มยำกุ้งหม้อไฟ", cal: 600, type: "noodle", img: "photo/มาม่าต้มยำกุ้งหม้อไฟ.JPG" },
    { name: "สปาเก็ตตี้คาโบนาร่า", cal: 750, type: "noodle", img: "photo/สปาเก็ตตี้คาโบนาร่า.JPG" },
    { name: "สปาเก็ตตี้ผัดขี้เมาทะเล", cal: 500, type: "noodle", img: "photo/สปาเก็ตตี้ผัดขี้เมาทะเล.JPG" },
    { name: "ยำวุ้นเส้นหมูสับ", cal: 150, type: "noodle", img: "photo/ยำวุ้นเส้นหมูสับ.JPG" },
    { name: "วุ้นเส้นผัดไข่", cal: 400, type: "noodle", img: "photo/วุ้นเส้นผัดไข่.JPG" },

    // --- อาหารจานเดียว (ข้าว) ---
    { name: "ข้าวมันไก่ต้ม", cal: 600, type: "rice", img: "photo/ข้าวมันไก่ต้ม.JPG" },
    { name: "ข้าวมันไก่ทอด", cal: 700, type: "rice", img: "photo/ข้าวมันไก่ทอด.JPG" },
    { name: "ข้าวผัดกะเพราหมูสับไข่ดาว", cal: 650, type: "rice", img: "photo/ข้าวผัดกระเพราไข่ดาว.JPG" },
    { name: "ข้าวผัดกะเพราหมูกรอบ", cal: 750, type: "rice", img: "photo/ข้าวผัดกระเพราหมูกรอบ.JPG" },
    { name: "ข้าวผัดหมู", cal: 550, type: "rice", img: "photo/ข้าวผัดหมู.JPG" },
    { name: "ข้าวผัดปู", cal: 600, type: "rice", img: "photo/ข้าวผัดปู.JPG" },
    { name: "ข้าวหมูแดงหมูกรอบ", cal: 650, type: "rice", img: "photo/ข้าวหมูเเดงหมูกรอบ.JPG" },
    { name: "ข้าวขาหมู", cal: 690, type: "rice", img: "photo/ข้าวขาหมู.JPG" },
    { name: "ข้าวไข่เจียวหมูสับ", cal: 480, type: "rice", img: "photo/ข้าวไข่เจียวหมูสับ.JPG" },
    { name: "ข้าวคลุกกะปิ", cal: 600, type: "rice", img: "photo/ข้าวคลุกกะปิ.JPG" },
    { name: "ข้าวหมูทอดกระเทียม", cal: 550, type: "rice", img: "photo/ข้าวหมูทอดกระเทียม.JPG" },
    { name: "ข้าวแกงกะหรี่ญี่ปุ่น", cal: 750, type: "rice", img: "photo/ข้าวเเกงกระหรี่ญี่ปุ่น.JPG" },
    { name: "ข้าวหมกไก่", cal: 550, type: "rice", img: "photo/ข้าวหมกไก่.JPG" },
    { name: "ข้าวยำไก่แซ่บ", cal: 600, type: "rice", img: "photo/ข้าวยำไก่เเซ่บ.JPG" },
    { name: "ข้าวพะแนงหมู", cal: 550, type: "rice", img: "photo/ข้าวพะเเนงหมู.JPG" },
    { name: "ข้าวหน้าเป็ด", cal: 500, type: "rice", img: "photo/ข้าวหน้าเป็ด.JPG" },
    { name: "ข้าวผัดสับปะรด", cal: 600, type: "rice", img: "photo/ข้าวผัดสับปะรด.JPG" },
    { name: "โจ๊กหมูใส่ไข่", cal: 250, type: "rice", img: "photo/โจ๊กหมูใส่ไข่.JPG" },
    { name: "ข้าวต้มกุ้ง", cal: 200, type: "rice", img: "photo/ข้าวต้มกุ้ง.JPG" },
    { name: "ข้าวราดผัดผักบุ้งหมูกรอบ", cal: 600, type: "rice", img: "photo/ข้าวราดผัดผักบุ้งหมูกรอบ.JPG" },
    { name: "ข้าวราดผัดพริกแกงหมู", cal: 550, type: "rice", img: "photo/ข้าวราดผัดพริกเเกงหมู.JPG" },

    // --- อาหารอีสาน / ยำ / ส้มตำ ---
    { name: "ส้มตำไทย", cal: 120, type: "clean", img: "photo/ส้มตำไทย.jpg" },
    { name: "ส้มตำปูปลาร้า", cal: 100, type: "clean", img: "photo/ส้มตำปูปลาร้า.jpg" },
    { name: "ตำข้าวโพดไข่เค็ม", cal: 350, type: "clean", img: "photo/ตำข้าวโพดไข่เค็ม.jpg" },
    { name: "น้ำตกหมู", cal: 200, type: "clean", img: "photo/น้ำตกหมู.jpg" },
    { name: "ไก่ย่างข้าวเหนียว", cal: 400, type: "rice", img: "photo/ไก่ย่างข้าวเหนียว.jpg" },
    { name: "คอหมูย่าง", cal: 400, type: "rice", img: "photo/คอหมูย่าง.png" },
    { name: "ต้มแซ่บกระดูกอ่อน", cal: 180, type: "clean", img: "photo/ต้มแซ่บกระดูกอ่อน.png" },
    { name: "ซุปหน่อไม้", cal: 100, type: "clean", img: "photo/ซุปหน่อไม้.jpg" },
    { name: "ยำมาม่ารวมมิตร", cal: 300, type: "noodle", img: "photo/ยำมาม่ารวมมิตร.jpg" },
    { name: "ยำไข่ดาว", cal: 250, type: "clean", img: "photo/ยำไข่ดาว.png" },
    { name: "จิ้มจุ่มรวมมิตร", cal: 400, type: "clean", img: "photo/จิ้มจุ่มรวมมิตร.jpg" },

    // --- อาหารคลีน / สุขภาพ ---
    { name: "สลัดอกไก่", cal: 300, type: "clean", img: "photo/สลัดอกไก่.JPG" },
    { name: "สลัดทูน่า", cal: 350, type: "clean", img: "photo/สลัดทูน่า.JPG" },
    { name: "ข้าวไรซ์เบอร์รี่ + ปลานึ่งมะนาว", cal: 350, type: "clean", img: "photo/ข้าวไรซ์เบอร์รี่ปลานึ่งมะนาว.JPG" },
    { name: "อกไก่ปั่น", cal: 180, type: "clean", img: "photo/อกไก่ปั่น.JPG" },
    { name: "ก๋วยเตี๋ยวลุยสวน", cal: 200, type: "clean", img: "photo/ก๋วยเตี๋ยวลุยสวน.JPG" },
    { name: "แกงจืดเต้าหู้หมูสับ + ข้าวกล้อง", cal: 300, type: "clean", img: "photo/เเกงจืดเต้าหู้หมูสับ.JPG" },
    { name: "ไข่ต้ม (2 ฟอง)", cal: 160, type: "clean", img: "photo/ไข่ต้ม2ฟอง.JPG" },
    { name: "แซนวิชอกไก่", cal: 250, type: "clean", img: "photo/เเซนวิชอกไก่.JPG" },
    { name: "โยเกิร์ต + กราโนล่า", cal: 250, type: "clean", img: "photo/โยเกิร์ต.JPG" },
    { name: "น้ำพริกผักต้ม + ไข่ต้ม", cal: 250, type: "clean", img: "photo/น้ำพริกผักต้ม.JPG" },
    { name: "เมี่ยงปลาเผา", cal: 300, type: "clean", img: "photo/เมี่ยงปลาเผา.JPG" },

    // --- อาหารตะวันตก / Fast Food ---
    { name: "แฮมเบอร์เกอร์หมู", cal: 500, type: "rice", img: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&w=800" },
    { name: "ชีสเบอร์เกอร์", cal: 600, type: "rice", img: "photo/ชีสเบอร์เกอร์.JPG" },
    { name: "พิซซ่าฮาวายเอี้ยน (2 ชิ้น)", cal: 600, type: "rice", img: "photo/พิซซ่าฮาวายเอี้ยน.JPG" },
    { name: "เฟรนช์ฟรายส์", cal: 400, type: "rice", img: "photo/เฟรนซ์ฟรายส์.JPG" },
    { name: "ไก่ทอด (1 ชิ้น)", cal: 300, type: "rice", img: "photo/ไก่ทอด.JPG" },
    { name: "สเต็กหมูพริกไทยดำ", cal: 600, type: "rice", img: "photo/สเต็กหมูพริกไทยดำ.JPG" },
    { name: "สเต็กปลาแซลมอน", cal: 500, type: "clean", img: "photo/สเต็กปลาแซลมอน.JPG" },
    { name: "ซุปเห็ดทรัฟเฟิล", cal: 300, type: "rice", img: "photo/ซุปเห็ดทรัฟเฟิล.JPG" },
    { name: "ซีซาร์สลัด", cal: 400, type: "clean", img: "photo/ซีซาร์สลัด.JPG" },

    // --- อาหารใต้ / รสจัด ---
    { name: "คั่วกลิ้งหมู + ข้าว", cal: 500, type: "rice", img: "photo/คั่วกลิ้งหมู.JPG" },
    { name: "แกงไตปลา + ขนมจีน", cal: 400, type: "noodle", img: "photo/เเกงไตปลา.JPG" },
    { name: "แกงเหลืองหน่อไม้ดอง", cal: 350, type: "clean", img: "photo/เเกงเหลืองหน่อไม้.JPG" },
    { name: "ไก่ทอดหาดใหญ่ + ข้าวเหนียว", cal: 600, type: "rice", img: "photo/ไก่ทอดหาดใหญ่.JPG" },
    { name: "ผัดสะตอกะปิกุ้ง", cal: 500, type: "rice", img: "photo/ผัดสะตอกะปิกุ้ง.JPG" },
    
    // --- อื่นๆ เพิ่มเติม ---
    { name: "ต้มยำกุ้งน้ำข้น + ข้าว", cal: 500, type: "rice", img: "photo/ต้มยำกุ้งน้ำข้น.JPG" },
    { name: "ต้มข่าไก่ + ข้าว", cal: 550, type: "rice", img: "photo/ต้มข่าไก่.JPG" },
    { name: "หมูสามชั้นทอดน้ำปลา + ข้าว", cal: 700, type: "rice", img: "photo/หมูสามชั้นทอดน้ำปลา.JPG" },
    { name: "ไข่เจียวปู", cal: 400, type: "rice", img: "photo/ไข่เจียวปู.JPG" },
    { name: "ปลาหมึกผัดไข่เค็ม", cal: 550, type: "rice", img: "photo/ปลาหมึกผัดไข่เค็ม.JPG" },
    { name: "กุ้งอบวุ้นเส้น", cal: 400, type: "noodle", img: "photo/กุ้งอบวุ้นเส้น.JPG" },
    { name: "ปลากะพงทอดน้ำปลา", cal: 450, type: "rice", img: "photo/ปลากระพงทอดน้ำปลา.JPG" },
    { name: "ทอดมันปลากราย", cal: 350, type: "rice", img: "photo/ทอดมันปลากราย.JPG" }
];